name: Load proxies
permissions: write-all
on:
  push:
    branches:
      - "main"
    paths:
      - ".github/**"
  schedule:
    - cron: '*/15 * * * *'

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: LeetCode
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.leetcode.svg
          token: NOT_NEEDED
          plugin_leetcode_user: batsura-vs
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
      - name: Stats
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes

