name: Load proxies
permissions: write-all
on:
  push:
    branches:
      - "main"
    paths:
      - ".github/**"
  schedule:
    - cron: '*/15 * * * *'

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: LeetCode
        uses: lowlighter/metrics@latest
        with:
          filename: full.svg
          token: ${{ secrets.METRICS_TOKEN }}
          
          plugin_leetcode: yes
          plugin_leetcode_user: batsura-vs
          plugin_leetcode_sections: solved, skills, recent
          
          plugin_lines: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
            
          plugin_languages: yes
          plugin_languages_limit: 4
          
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X


